baseurl = "http://waziup.github.io/web"
languageCode = "us-en"
title = "my new web site"
[params]
  description = "I <3 making web site"
  mainIcon = "/img/waziup.png"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "github"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "linkedin"
    url = ""